#!/bin/bash

while : # I'm aware that while : is ugly, but it runs just that tiny bit faster and uses just that tiny bit less RAM.
do
    # Start in the background so the script will keep running
    cmatrix -a &
    sleep 5
    killall -INT cmatrix
    htop &
    sleep 5
    killall -INT htop
    # htop doesn't automatically clear itself when you close it (at least on TTYs), so we have to clear for it)
    clear
    # sl only runs for so long and then clears itself, so we don't need to sleep/kill or clear
    sl -aeF # -aeF shows people yelling help out of the windows of the train, allows you to exit it with ctrl+c, and makes the train fly (man sl)
done
